POST http://localhost:3001/sha256
Content-Type: application/json

{
  "text": "mensagem de teste"
}

###
POST http://localhost:3001/rsa
Content-Type: application/json

{
  "text": "mensagem de teste"
}

###
POST http://localhost:3001/base64/encode
Content-Type: application/json

{
  "text": "mensagem de teste"
}

###
POST http://localhost:3001/base64/decode
Content-Type: application/json

{
  "text": "bWVuc2FnZW0gc2VjcmV0YQ=="
}